### ISSUE TITLE
flow-send Does not work on freebsd 7.0-STABLE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adsr/flow-tools#6]
```
flow-send Does not work on freebsd 7.0-STABLE
flow-tools-0.68_6 
example:
# flow-gen -V5 | flow-send -d9 127.0.0.1/127.0.0.1/9990
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: send(): Invalid argument
flow-send: processed 1000 flows
  sys:   seconds=0.002 flows/second=389863.547758
  wall:  seconds=0.002 flows/second=435540.069686

```

Original issue reported on code.google.com by `tempo...@gmail.com` on 11 Nov 2008 at 10:47
